# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pyqt5gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(332, 169)
        MainWindow.setMinimumSize(QtCore.QSize(332, 169))
        MainWindow.setMaximumSize(QtCore.QSize(332, 169))
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: #1C1C1F;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 331, 248))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame.setFont(font)
        self.frame.setStyleSheet(
            "* {\n"
            "    color: white;\n"
            "}\n"
            "\n"
            "QCheckBox::indicator {\n"
            "    border-radius: 4px;\n"
            "    width: 16px;\n"
            "    height: 16px;\n"
            "}\n"
            "\n"
            "QCheckBox::indicator::unchecked {\n"
            "    border: 1px solid #5A5A5A;\n"
            "}\n"
            "\n"
            "QCheckBox::indicator::checked {\n"
            "    border: 1px solid #ff4d4d;\n"
            "    background: #ff4d4d;\n"
            "}"
        )
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.run_button = QtWidgets.QPushButton(self.frame)
        self.run_button.setGeometry(QtCore.QRect(244, 142, 76, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.run_button.setFont(font)
        self.run_button.setStyleSheet(
            "QPushButton {\n"
            "  background-color: #ff4d4d;\n"
            "  border-radius: 8px;\n"
            "  color: #FFFFFF;\n"
            "}\n"
            "\n"
            "\n"
            "QPushButton:hover:!pressed {\n"
            "  background-color: #f26363;\n"
            "}"
        )
        self.run_button.setObjectName("run_button")
        self.dotnet_framework_checkbox = QtWidgets.QCheckBox(self.frame)
        self.dotnet_framework_checkbox.setGeometry(QtCore.QRect(4, 20, 131, 21))
        self.dotnet_framework_checkbox.setStyleSheet("")
        self.dotnet_framework_checkbox.setObjectName("dotnet_framework_checkbox")
        self.restore_ms_photo_viewer_checkbox = QtWidgets.QCheckBox(self.frame)
        self.restore_ms_photo_viewer_checkbox.setGeometry(QtCore.QRect(4, 83, 151, 21))
        self.restore_ms_photo_viewer_checkbox.setStyleSheet("")
        self.restore_ms_photo_viewer_checkbox.setObjectName(
            "restore_ms_photo_viewer_checkbox"
        )
        self.debloat_label = QtWidgets.QLabel(self.frame)
        self.debloat_label.setGeometry(QtCore.QRect(167, 2, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.debloat_label.setFont(font)
        self.debloat_label.setStyleSheet("color: #ff4d4d;")
        self.debloat_label.setObjectName("debloat_label")
        self.disable_bloat_services_checkbox = QtWidgets.QCheckBox(self.frame)
        self.disable_bloat_services_checkbox.setGeometry(QtCore.QRect(166, 20, 131, 21))
        self.disable_bloat_services_checkbox.setStyleSheet("")
        self.disable_bloat_services_checkbox.setObjectName(
            "disable_bloat_services_checkbox"
        )
        self.disable_gamedvr_checkbox = QtWidgets.QCheckBox(self.frame)
        self.disable_gamedvr_checkbox.setGeometry(QtCore.QRect(166, 41, 131, 21))
        self.disable_gamedvr_checkbox.setStyleSheet("")
        self.disable_gamedvr_checkbox.setObjectName("disable_gamedvr_checkbox")
        self.remove_telemetry_keys_checkbox = QtWidgets.QCheckBox(self.frame)
        self.remove_telemetry_keys_checkbox.setGeometry(QtCore.QRect(166, 62, 151, 21))
        self.remove_telemetry_keys_checkbox.setStyleSheet("")
        self.remove_telemetry_keys_checkbox.setObjectName(
            "remove_telemetry_keys_checkbox"
        )
        self.uninstall_ms_onedrive = QtWidgets.QCheckBox(self.frame)
        self.uninstall_ms_onedrive.setGeometry(QtCore.QRect(166, 104, 161, 21))
        self.uninstall_ms_onedrive.setStyleSheet("")
        self.uninstall_ms_onedrive.setObjectName("uninstall_ms_onedrive")
        self.optimizations_label = QtWidgets.QLabel(self.frame)
        self.optimizations_label.setGeometry(QtCore.QRect(6, 1, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.optimizations_label.setFont(font)
        self.optimizations_label.setStyleSheet("color: #ff4d4d;")
        self.optimizations_label.setObjectName("optimizations_label")
        self.disable_mouse_acceleration_checkbox = QtWidgets.QCheckBox(self.frame)
        self.disable_mouse_acceleration_checkbox.setGeometry(
            QtCore.QRect(4, 41, 161, 21)
        )
        self.disable_mouse_acceleration_checkbox.setStyleSheet("")
        self.disable_mouse_acceleration_checkbox.setObjectName(
            "disable_mouse_acceleration_checkbox"
        )
        self.fix_keyboard_input_delay_checkbox = QtWidgets.QCheckBox(self.frame)
        self.fix_keyboard_input_delay_checkbox.setGeometry(QtCore.QRect(4, 62, 151, 21))
        self.fix_keyboard_input_delay_checkbox.setStyleSheet("")
        self.fix_keyboard_input_delay_checkbox.setObjectName(
            "fix_keyboard_input_delay_checkbox"
        )
        self.ultimate_power_plan_checkbox = QtWidgets.QCheckBox(self.frame)
        self.ultimate_power_plan_checkbox.setGeometry(QtCore.QRect(4, 104, 121, 21))
        self.ultimate_power_plan_checkbox.setStyleSheet("")
        self.ultimate_power_plan_checkbox.setObjectName("ultimate_power_plan_checkbox")
        self.visual_tweaks_checkbox = QtWidgets.QCheckBox(self.frame)
        self.visual_tweaks_checkbox.setGeometry(QtCore.QRect(4, 146, 101, 21))
        self.visual_tweaks_checkbox.setStyleSheet("")
        self.visual_tweaks_checkbox.setObjectName("visual_tweaks_checkbox")
        self.select_all_button = QtWidgets.QPushButton(self.frame)
        self.select_all_button.setGeometry(QtCore.QRect(165, 142, 73, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.select_all_button.setFont(font)
        self.select_all_button.setStyleSheet(
            "QPushButton {\n"
            "  background-color: #ff4d4d;\n"
            "  border-radius: 8px;\n"
            "  color: #FFFFFF;\n"
            "}\n"
            "\n"
            "\n"
            "QPushButton:hover:!pressed {\n"
            "  background-color: #f26363;\n"
            "}"
        )
        self.select_all_button.setObjectName("select_all_button")
        self.uninstall_ms_apps_checkbox = QtWidgets.QCheckBox(self.frame)
        self.uninstall_ms_apps_checkbox.setGeometry(QtCore.QRect(166, 83, 141, 21))
        self.uninstall_ms_apps_checkbox.setStyleSheet("")
        self.uninstall_ms_apps_checkbox.setObjectName("uninstall_ms_apps_checkbox")
        self.performance_tweaks_checkbox = QtWidgets.QCheckBox(self.frame)
        self.performance_tweaks_checkbox.setGeometry(QtCore.QRect(4, 125, 131, 21))
        self.performance_tweaks_checkbox.setStyleSheet("")
        self.performance_tweaks_checkbox.setObjectName("performance_tweaks_checkbox")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Windows Debloat"))
        self.run_button.setText(_translate("MainWindow", "Run"))
        self.dotnet_framework_checkbox.setText(
            _translate("MainWindow", ".NET Framework 3.5")
        )
        self.restore_ms_photo_viewer_checkbox.setText(
            _translate("MainWindow", "Restore MS Photo Viewer")
        )
        self.debloat_label.setText(_translate("MainWindow", "Debloat"))
        self.disable_bloat_services_checkbox.setText(
            _translate("MainWindow", "Disable Bloat Services")
        )
        self.disable_gamedvr_checkbox.setText(
            _translate("MainWindow", "Disable GameDVR")
        )
        self.remove_telemetry_keys_checkbox.setText(
            _translate("MainWindow", "Remove Telemetry Keys")
        )
        self.uninstall_ms_onedrive.setText(
            _translate("MainWindow", "Uninstall Microsoft OneDrive")
        )
        self.optimizations_label.setText(_translate("MainWindow", "Optimizations"))
        self.disable_mouse_acceleration_checkbox.setText(
            _translate("MainWindow", "Disable Mouse Acceleration")
        )
        self.fix_keyboard_input_delay_checkbox.setText(
            _translate("MainWindow", "Fix Keyboard Input Delay")
        )
        self.ultimate_power_plan_checkbox.setText(
            _translate("MainWindow", "Ultimate Power Plan")
        )
        self.visual_tweaks_checkbox.setText(_translate("MainWindow", "Visual Tweaks"))
        self.select_all_button.setText(_translate("MainWindow", "Select All"))
        self.uninstall_ms_apps_checkbox.setText(
            _translate("MainWindow", "Uninstall Microsoft Apps")
        )
        self.performance_tweaks_checkbox.setText(
            _translate("MainWindow", "Performance Tweaks")
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
